name: Node.js Package

on:
  push:
    branches:
      master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Setup Deps
        run: npm ci
      - name: Lintint
        run: npm run lint
      - name: Testing
        run: npm run test

  on-failure:
    permissions: write-all
    name: on-failure
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ always() && contains(needs.*.result, 'failure') && github.ref != 'refs/heads/master' }}
    steps:
      - uses: actions/checkout@v4
      - name: Save the PR number in an artifact
        shell: bash
        env:
          PR_NUM: ${{ github.event.number }}
        run: echo $PR_NUM > pr_num.txt

      - name: Upload the PR number
        uses: actions/upload-artifact@v3
        with:
          name: pr_num
          path: ./pr_num.txt

